### ISSUE TITLE
TypeError: expected Tensor as element 0 in argument 0, but got int

### ISSUE THREAD

**Issue by matzyr** [nschapeler/GDBot#2]
The bot ran fine for the first 50 episodes, then it leaves this error before crashing

Traceback (most recent call last):
  File "C\Users\naman\Desktop\GDBot-master\GDBot.py", line 239, in <module> optimize_model()
  File "C\Users\naman\Desktop\GDBot-master\GDBot.py", line 152, in optimize_model action_batch = torch.cat(batch.action)
TypeError: expected Tensor as element 0 in argument 0, but got int

**Comment by matzyr** [comment]
:(

**Comment by BitComputer64** [comment]
same here

**Comment by BashBunny69** [comment]
Any update?

**Comment by kalamy13e45** [comment]
Guess not.
