### ISSUE TITLE
Requirements.txt won't install

### ISSUE THREAD

**Issue by DrMeepso** [nschapeler/GDBot#4]
i keep getting this error

```
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\theen\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\theen\\AppData\\Local\\Temp\\pip-install-0txzhvbw\\pyobjc-framework-quartz_daa10fa6a9104fd5b65fc33da7afe157\\setup.py'"'"'; __file__='"'"'C:\\Users\\theen\\AppData\\Local\\Temp\\pip-install-0txzhvbw\\pyobjc-framework-quartz_daa10fa6a9104fd5b65fc33da7afe157\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\theen\AppData\Local\Temp\pip-pip-egg-info-f9lqsf7b'
         cwd: C:\Users\theen\AppData\Local\Temp\pip-install-0txzhvbw\pyobjc-framework-quartz_daa10fa6a9104fd5b65fc33da7afe157\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\theen\AppData\Local\Temp\pip-install-0txzhvbw\pyobjc-framework-quartz_daa10fa6a9104fd5b65fc33da7afe157\setup.py", line 64, in <module>
        Extension(
      File "C:\Users\theen\AppData\Local\Temp\pip-install-0txzhvbw\pyobjc-framework-quartz_daa10fa6a9104fd5b65fc33da7afe157\pyobjc_setup.py", line 414, in Extension
        os_level = get_os_level()
      File "C:\Users\theen\AppData\Local\Temp\pip-install-0txzhvbw\pyobjc-framework-quartz_daa10fa6a9104fd5b65fc33da7afe157\pyobjc_setup.py", line 200, in get_os_level
        with open("/System/Library/CoreServices/SystemVersion.plist", "rb") as fp:
    FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/CoreServices/SystemVersion.plist'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by nschapeler** [comment]
Have you looked at https://github.com/nschapeler/GDBot/issues/3#issuecomment-685067570?

**Comment by EvdokDima** [comment]
C:\Users\User>pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by cryptopapi997** [comment]
By your command, I can see you're in the `C:\Users\User` directory. You need to be inside the `GDBot` (this repo) directory for this to work.
