### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable PIP

### ISSUE THREAD

**Issue by EvdokDima** [nschapeler/GDBot#6]
C:\Users\User\Desktop\GDBot-master>pip install -r requirements.txt
Collecting numpy (from -r requirements.txt (line 1))
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/2f/2a/34fe0b64e78347f4ea128868df0034a97e0f92b476f62947b0976caba820/numpy-1.25.1-cp311-cp311-win_amd64.whl.metadata
  Downloading numpy-1.25.1-cp311-cp311-win_amd64.whl.metadata (5.7 kB)
Collecting opencv-python (from -r requirements.txt (line 2))
  Obtaining dependency information for opencv-python from https://files.pythonhosted.org/packages/a6/08/583e1d8d589e80a702815f58daa317bd469a32c7dc339394e2a0dc14318b/opencv_python-4.8.0.74-cp37-abi3-win_amd64.whl.metadata
  Downloading opencv_python-4.8.0.74-cp37-abi3-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: torch in c:\users\user\appdata\local\programs\python\python311\lib (from -r requirements.txt (line 3)) (2.0.1)
Collecting torchvision (from -r requirements.txt (line 4))
  Downloading torchvision-0.15.2-cp311-cp311-win_amd64.whl (1.2 MB)
     ---------------------------------------- 1.2/1.2 MB 3.8 MB/s eta 0:00:00
Collecting pyobjc-framework-Quartz (from -r requirements.txt (line 5))
  Downloading pyobjc-framework-Quartz-9.2.tar.gz (3.9 MB)
     ---------------------------------------- 3.9/3.9 MB 10.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-e56u5cvz\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-e56u5cvz\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-e56u5cvz\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 68, in <module>
        File "C:\Users\User\AppData\Local\Temp\pip-install-x60kfd3j\pyobjc-framework-quartz_c2890733cb234c7892ba853630950c2d\pyobjc_setup.py", line 469, in Extension
          if "clang" in get_config_var("CC"):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      TypeError: argument of type 'NoneType' is not iterable
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by cryptopapi997** [comment]
Hey thank you for opening this issue - I unfortunately don't have the time to personally maintain this project anymore, but if you'd like to open a PR fixing this, I'd be happy to review & merge.

**Comment by EvdokDima** [comment]
pyobjc-framework-Quartz for MacOS, but i use Windows. I just didn't use this package and everything worked for me. Use psychopy for Windows

**Comment by cryptopapi997** [comment]
Awesome, thanks for figuring this out! If I understand correctly you just replaced every occurence in the code of `pyobjc-framework-Quartz` with `psychopy` and it worked?

**Comment by EvdokDima** [comment]
I did not used psychopy and it worked. And **compare_ssim**  in **skimage.metrics** was renamed to compare_ssim. Also I have problem with **optimize_model()** so i deleted it.
